// Verifies the LLM Coach Report panel against REAL services: the NEXUS API
// on :8100 (which in turn calls the football backend on :8000 and a local
// Ollama model), rendered by the real dashboard on :3000.
//
// Nothing here is stubbed or route-intercepted. The point of this spec is
// exactly the gap a `npm run build` cannot close: that CoachReport.jsx
// renders the shape the API actually returns, including the two states that
// matter most for honesty -- the partial-report banner and the
// "what could not be measured" list.
//
// The report is generated by a live model, so this spec asserts on
// STRUCTURE (sections, evidence, metric names), never on narrative wording.

import { chromium } from 'playwright';

const BASE = process.env.BASE || 'http://localhost:3000';
const API = process.env.API || 'http://localhost:8000';
const NEXUS = process.env.NEXUS || 'http://localhost:8100';

// A coach report waits on a local LLM; generation dominates this budget.
const REPORT_TIMEOUT_MS = Number(process.env.REPORT_TIMEOUT_MS || 600_000);

let passed = 0;
let failed = 0;

function check(name, condition, detail = '') {
  if (condition) {
    passed += 1;
    console.log(`   ok  ${name}`);
  } else {
    failed += 1;
    console.log(`  FAIL ${name}${detail ? ` — ${detail}` : ''}`);
  }
}

async function pickMatch() {
  if (process.env.MATCH) return process.env.MATCH;
  const list = await (await fetch(`${API}/api/matches`)).json();
  for (const item of list) {
    if (item.job_status === 'completed') return item.match_id;
  }
  return null;
}

async function run() {
  const matchId = await pickMatch();
  if (!matchId) {
    console.log('no completed match available — process a video first');
    process.exit(1);
  }
  console.log(`match under test: ${matchId}`);

  // Fetch the report once up front. It is the same call the UI makes, and
  // having the payload lets every DOM assertion below be checked against
  // what the API actually said rather than against hardcoded text.
  console.log('requesting coach report from NEXUS (live model, may take minutes)...');
  const started = Date.now();
  const response = await fetch(`${NEXUS}/api/sports/${matchId}/report`, {
    signal: AbortSignal.timeout(REPORT_TIMEOUT_MS),
  });
  const report = await response.json();
  console.log(`report received in ${((Date.now() - started) / 1000).toFixed(1)}s`);

  console.log('\n0. THE API CONTRACT THE UI RENDERS');
  check('report responded 200', response.status === 200, `got ${response.status}`);
  check('narrative is non-empty', Boolean(report.narrative?.trim()));
  check('game_plan is present', Boolean(report.game_plan));
  check('findings is an array', Array.isArray(report.findings));
  check('unavailable_metrics is an array', Array.isArray(report.unavailable_metrics));
  check('timeline_sections is present', Boolean(report.timeline_sections));

  const browser = await chromium.launch();
  const page = await browser.newPage();
  const pageErrors = [];
  page.on('pageerror', (error) => pageErrors.push(error.message));

  try {
    // Deep-link straight to the match analysis tab, scoped to this match.
    // Same URL form the other specs use; clicking the tab is unreliable
    // because the dashboard mounts inside the marketing shell and the tab
    // strip is off-screen until the shell scrolls.
    await page.goto(`${BASE}/?match=${matchId}#dashboard/match`, {
      waitUntil: 'networkidle',
    });
    await page.waitForTimeout(2500);

    console.log('\n1. THE PANEL IS REACHABLE');
    const heading = page.locator('text=/LLM Coach Report/i').first();
    await heading.scrollIntoViewIfNeeded().catch(() => {});
    check('the "LLM Coach Report" section heading renders', (await heading.count()) > 0);

    console.log('\n2. THE REPORT RENDERS (waiting on the live model)');
    const reportRoot = page.locator('.dash-coach-report');
    await reportRoot
      .waitFor({ state: 'visible', timeout: REPORT_TIMEOUT_MS })
      .catch(() => {});
    const rendered = (await reportRoot.count()) > 0;
    check('the coach report root rendered', rendered);

    if (!rendered) {
      const empty = await page.locator('.dash-state-label, .dash-absent').first().innerText().catch(() => '');
      console.log(`  (panel showed instead: ${empty.slice(0, 200)})`);
    } else {
      const bodyText = await reportRoot.innerText();

      console.log('\n3. MEASURED DATA, NOT JUST PROSE');
      // The UI issues its own request, and reports are generated per call
      // rather than cached -- so the page's narrative is a DIFFERENT
      // generation from the one fetched above. Comparing the two texts
      // would fail on model non-determinism, not on a UI defect. Assert
      // instead that a substantial narrative was rendered at all.
      const narrativeText = await page
        .locator('.dash-narrative')
        .innerText()
        .catch(() => '');
      check('a narrative block rendered', narrativeText.trim().length > 200);
      check(
        'the narrative is labelled as the generated field',
        /generated by/i.test(bodyText),
      );
      check(
        'coverage is displayed',
        /\d+\.\d%/.test(bodyText),
        'expected a formatted coverage percentage',
      );
      check('the model id is displayed', bodyText.includes(report.model_used));

      console.log('\n4. PARTIAL-REPORT HONESTY');
      const partialChip = page.locator('.dash-coach-header', { hasText: /partial|full report/i });
      check('a partial/full report chip is shown', (await partialChip.count()) > 0);
      if (report.is_partial) {
        check(
          'the partial reason is surfaced to the coach',
          bodyText.toLowerCase().includes('partial'),
        );
      }

      console.log('\n5. GAME PLAN SECTIONS');
      const plan = report.game_plan;
      check('the Game Plan heading renders', /game plan/i.test(bodyText));
      if (plan.proposed_shape) {
        check(
          'the proposed shape is rendered',
          bodyText.includes(plan.proposed_shape.shape),
          plan.proposed_shape.shape,
        );
      }
      if (plan.opponent_weaknesses.length) {
        const first = plan.opponent_weaknesses[0];
        check('a measured weakness label is rendered', bodyText.includes(first.label), first.label);
        check(
          'its evidence string is rendered (traceable claim)',
          bodyText.includes(first.evidence.slice(0, 30)),
        );
      }
      if (plan.adjustments.length) {
        const first = plan.adjustments[0];
        check(
          'an in-game adjustment is rendered',
          bodyText.includes(first.instruction.slice(0, 40)),
        );
        check(
          'the adjustment names the weakness it targets',
          bodyText.includes(first.targets_weakness),
          first.targets_weakness,
        );
      }

      console.log('\n6. WHAT COULD NOT BE MEASURED');
      check('the unavailable section renders', /could not be measured/i.test(bodyText));
      if (report.unavailable_metrics.length) {
        const name = report.unavailable_metrics[0].split(':')[0].trim();
        check(`an unavailable metric name is listed (${name})`, bodyText.includes(name));
      }
      const missing = report.timeline_sections?.missing || [];
      if (missing.length) {
        check(
          'missing timeline sections are reported, not silently dropped',
          missing.every((section) => bodyText.includes(section)),
          `expected ${missing.join(', ')}`,
        );
      }
    }

    console.log('\n7. PAGE HEALTH');
    check('no uncaught page errors', pageErrors.length === 0, pageErrors.join(' | '));
  } finally {
    await browser.close();
  }

  console.log(`\n${passed} passed, ${failed} failed`);
  process.exit(failed ? 1 : 0);
}

run().catch((error) => {
  console.error('test harness error:', error);
  process.exit(1);
});
