"""
Regenerates docs/pipeline_latency_profile.md from REAL PipelineLatencyReport
data written by backend/tasks.py during an actual pipeline run.

This script is the only thing that may write that file. Hand-typed,
precise-looking per-stage numbers with no instrumentation behind them are a
fabricated benchmark, not a measured one.

Usage (after at least one job has completed successfully):
    python3 scripts/generate_latency_report.py [--job-id JOB_ID] [--last N]

If no job has completed yet, this refuses to write placeholder numbers --
it writes an honest "no runs yet" doc instead and exits non-zero, so CI or
a pre-demo checklist can catch "we never actually profiled this" instead
of silently shipping stale/fake numbers.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

from backend.database.models import AnalysisResult, ProcessingJob, ProcessingStatus  # noqa: E402
from backend.database.session import SessionLocal  # noqa: E402

DOC_PATH = Path(__file__).resolve().parents[1] / "docs" / "pipeline_latency_profile.md"

# Stage details carry the checkpoint path the run actually used, e.g.
# "model=D:\...\models\yolo\player_v1\weights\best.pt". That is right for the
# run and wrong for a committed doc: it leaks one machine's directory layout.
# Keep everything from the `models` directory down, with forward slashes.
_ABSOLUTE_MODEL_PATH = re.compile(r"(?:[A-Za-z]:)?[\\/][^\s|]*?[\\/](models[\\/][^\s|]+)")


def _portable_detail(detail: str | None) -> str | None:
    if not detail:
        return detail
    return _ABSOLUTE_MODEL_PATH.sub(lambda m: m.group(1).replace("\\", "/"), detail)

NO_DATA_TEMPLATE = """# Pipeline Latency Profile

**No completed pipeline runs found yet.**

This file is generated exclusively by `scripts/generate_latency_report.py`
from real `PipelineLatencyReport` data (see `backend/pipeline/latency.py`)
captured during an actual `backend/tasks.py::process_video_job` run. It is
never hand-edited with estimated or illustrative numbers -- a previous
version of this file was, and that's a real credibility risk if a judge
asks to see the profiling code behind a number that doesn't exist.

Run the pipeline against a real match clip (`POST /api/videos/upload`),
wait for it to complete, then re-run:

```
python3 scripts/generate_latency_report.py
```

Generated at: {generated_at}
"""

REPORT_TEMPLATE = """# Pipeline Latency Profile

**This file is auto-generated by `scripts/generate_latency_report.py` from
real, measured pipeline runs. Do not hand-edit -- your changes will be
overwritten the next time this script runs, and (more importantly) any
number here that wasn't produced by an actual run undermines the whole
point of this document.**

Source: job `{job_id}` (match `{match_id}`), completed {generated_at}.

## Stage breakdown

| Stage | Seconds | Detail |
|---|---|---|
{rows}

**Total measured latency: {total_seconds:.2f}s**

## How to reproduce

```
python3 scripts/generate_latency_report.py --job-id {job_id}
```

## Interpreting this

- If the slowest stage is `detection_tracking`, the bottleneck is YOLO
  inference + ByteTrack, not this project's own analytics code -- consider
  a smaller model variant or reduced `imgsz` (see `configs/models.yaml`)
  for the live demo clip specifically.
- If `db_write_tracking` is disproportionately large relative to
  `frames_processed`, revisit `FRAME_PERSIST_STRIDE`
  (`backend/pipeline/runner.py`) or switch the per-row `db.add()` calls in
  that stage to a true bulk insert.
- Numbers will vary run-to-run and hardware-to-hardware -- re-run this
  script on the actual demo machine shortly before presenting, don't trust
  a profile captured on a different laptop.
"""


def generate(job_id: str | None = None) -> int:
    db = SessionLocal()
    try:
        query = (
            db.query(AnalysisResult)
            .join(ProcessingJob, ProcessingJob.id == AnalysisResult.job_id)
            .filter(ProcessingJob.status == ProcessingStatus.completed)
        )
        if job_id:
            query = query.filter(AnalysisResult.job_id == job_id)

        result = query.order_by(AnalysisResult.created_at.desc()).first()

        if result is None or "pipeline_latency" not in (result.result_json or {}):
            DOC_PATH.write_text(NO_DATA_TEMPLATE.format(
                generated_at=datetime.now(UTC).isoformat()
            ))
            print(f"No completed run with a latency report found. Wrote placeholder to {DOC_PATH}.")
            return 1

        latency = result.result_json["pipeline_latency"]
        rows = "\n".join(
            f"| `{s['stage']}` | {s['seconds']:.4f} | {_portable_detail(s.get('detail')) or '-'} |"
            for s in latency["stages"]
        )
        DOC_PATH.write_text(REPORT_TEMPLATE.format(
            job_id=latency["job_id"],
            match_id=latency.get("match_id") or "unknown",
            generated_at=latency["generated_at"],
            rows=rows,
            total_seconds=latency["total_seconds"],
        ))
        print(f"Wrote real latency report ({len(latency['stages'])} stages, "
              f"{latency['total_seconds']:.2f}s total) to {DOC_PATH}.")
        return 0
    finally:
        db.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--job-id", default=None, help="Specific job to report on; defaults to the most recent completed run.")
    args = parser.parse_args()
    sys.exit(generate(job_id=args.job_id))
