"""baseline schema from models

Revision ID: 1f14a075761a
Revises: 
Create Date: 2026-09-17 22:59:48.475128

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1f14a075761a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('home_team', sa.String(length=255), nullable=False),
    sa.Column('away_team', sa.String(length=255), nullable=False),
    sa.Column('video_path', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('calibration_status',
    sa.Column('calibration_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('frame_start', sa.Integer(), nullable=False),
    sa.Column('frame_end', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('invalid_reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reprojection_error_m', sa.Float(), nullable=True),
    sa.Column('n_points', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'model', 'carried', 'none', name='calibrationsourcekind'), nullable=False),
    sa.Column('solved_on_frame', sa.Integer(), nullable=True),
    sa.Column('camera_motion', sa.String(length=16), nullable=True),
    sa.Column('camera_shift_px', sa.Float(), nullable=True),
    sa.Column('homography_matrix', sa.JSON(), nullable=True),
    sa.Column('method', sa.Enum('ml_trained', 'deterministic', 'heuristic_proxy', name='metricmethod'), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('calibration_id')
    )
    with op.batch_alter_table('calibration_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_status_frame_start'), ['frame_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_status_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_status_valid'), ['valid'], unique=False)

    op.create_table('frames',
    sa.Column('frame_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('frame_id')
    )
    with op.batch_alter_table('frames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frames_match_id'), ['match_id'], unique=False)

    op.create_table('player_metrics',
    sa.Column('metric_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('method', sa.Enum('ml_trained', 'deterministic', 'heuristic_proxy', name='metricmethod'), nullable=False),
    sa.Column('confidence', sa.Enum('normal', 'low_sample', 'low_upstream_confidence', name='metricconfidence'), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('sub_scores', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    with op.batch_alter_table('player_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_metrics_match_id'), ['match_id'], unique=False)

    op.create_table('player_tracking',
    sa.Column('tracking_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=True),
    sa.Column('pixel_x', sa.Float(), nullable=False),
    sa.Column('pixel_y', sa.Float(), nullable=False),
    sa.Column('pitch_x_m', sa.Float(), nullable=True),
    sa.Column('pitch_y_m', sa.Float(), nullable=True),
    sa.Column('homography_confidence', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('body_orientation_deg', sa.Float(), nullable=True),
    sa.Column('body_orientation_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('tracking_id')
    )
    with op.batch_alter_table('player_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_tracking_frame_id'), ['frame_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_tracking_match_id'), ['match_id'], unique=False)

    op.create_table('prematch_questionnaires',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('questionnaire_json', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prematch_questionnaires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prematch_questionnaires_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prematch_questionnaires_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prematch_questionnaires_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('psychology_assessments',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('cv_player_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('mental_readiness', sa.Float(), nullable=False),
    sa.Column('focus', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stress', sa.Float(), nullable=False),
    sa.Column('pressure_risk', sa.String(length=16), nullable=False),
    sa.Column('mental_performance_risk', sa.String(length=16), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('sub_scores', sa.JSON(), nullable=False),
    sa.Column('method', sa.Enum('ml_trained', 'deterministic', 'heuristic_proxy', name='metricmethod'), nullable=False),
    sa.Column('confidence_level', sa.Enum('normal', 'low_sample', 'low_upstream_confidence', name='metricconfidence'), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('submission_index', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    with op.batch_alter_table('psychology_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psychology_assessments_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_psychology_assessments_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_psychology_assessments_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_psychology_assessments_submission_index'), ['submission_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_psychology_assessments_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('team_metrics',
    sa.Column('metric_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_label', sa.String(length=64), nullable=True),
    sa.Column('method', sa.Enum('ml_trained', 'deterministic', 'heuristic_proxy', name='metricmethod'), nullable=False),
    sa.Column('confidence', sa.Enum('normal', 'low_sample', 'low_upstream_confidence', name='metricconfidence'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('sub_scores', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    with op.batch_alter_table('team_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_metrics_match_id'), ['match_id'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_match_id'), ['match_id'], unique=False)

    op.create_table('ball_detections',
    sa.Column('detection_id', sa.String(length=36), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('ball_x', sa.Float(), nullable=False),
    sa.Column('ball_y', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.frame_id'], ),
    sa.PrimaryKeyConstraint('detection_id')
    )
    with op.batch_alter_table('ball_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ball_detections_frame_id'), ['frame_id'], unique=False)

    op.create_table('events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('related_player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.String(length=64), nullable=True),
    sa.Column('pitch_x_m', sa.Float(), nullable=True),
    sa.Column('pitch_y_m', sa.Float(), nullable=True),
    sa.Column('homography_confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.frame_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_frame_id'), ['frame_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_match_id'), ['match_id'], unique=False)

    op.create_table('player_detections',
    sa.Column('detection_id', sa.String(length=36), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=True),
    sa.Column('team_assignment_confidence', sa.Float(), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.frame_id'], ),
    sa.PrimaryKeyConstraint('detection_id')
    )
    with op.batch_alter_table('player_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_detections_frame_id'), ['frame_id'], unique=False)

    op.create_table('prematch_health_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('questionnaire_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('submission_index', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('physical_readiness', sa.Float(), nullable=False),
    sa.Column('fatigue_score', sa.Float(), nullable=False),
    sa.Column('recovery_score', sa.Float(), nullable=False),
    sa.Column('performance_risk', sa.Enum('low', 'moderate', 'high', name='risklevel'), nullable=False),
    sa.Column('workload_risk', sa.Enum('low', 'moderate', 'high', name='risklevel'), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('method', sa.Enum('ml_trained', 'deterministic', 'heuristic_proxy', name='metricmethod'), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['prematch_questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prematch_health_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prematch_health_assessments_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prematch_health_assessments_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prematch_health_assessments_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prematch_health_assessments_questionnaire_id'), ['questionnaire_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_prematch_health_assessments_submission_index'), ['submission_index'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='processingstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_video_id'), ['video_id'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_results_job_id'), ['job_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_job_id'))

    op.drop_table('analysis_results')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_video_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('prematch_health_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prematch_health_assessments_submission_index'))
        batch_op.drop_index(batch_op.f('ix_prematch_health_assessments_questionnaire_id'))
        batch_op.drop_index(batch_op.f('ix_prematch_health_assessments_player_id'))
        batch_op.drop_index(batch_op.f('ix_prematch_health_assessments_match_id'))
        batch_op.drop_index(batch_op.f('ix_prematch_health_assessments_computed_at'))

    op.drop_table('prematch_health_assessments')
    with op.batch_alter_table('player_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_detections_frame_id'))

    op.drop_table('player_detections')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_match_id'))
        batch_op.drop_index(batch_op.f('ix_events_frame_id'))

    op.drop_table('events')
    with op.batch_alter_table('ball_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ball_detections_frame_id'))

    op.drop_table('ball_detections')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_match_id'))

    op.drop_table('videos')
    with op.batch_alter_table('team_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_metrics_match_id'))

    op.drop_table('team_metrics')
    with op.batch_alter_table('psychology_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psychology_assessments_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_psychology_assessments_submission_index'))
        batch_op.drop_index(batch_op.f('ix_psychology_assessments_player_id'))
        batch_op.drop_index(batch_op.f('ix_psychology_assessments_match_id'))
        batch_op.drop_index(batch_op.f('ix_psychology_assessments_computed_at'))

    op.drop_table('psychology_assessments')
    with op.batch_alter_table('prematch_questionnaires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prematch_questionnaires_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_prematch_questionnaires_player_id'))
        batch_op.drop_index(batch_op.f('ix_prematch_questionnaires_match_id'))

    op.drop_table('prematch_questionnaires')
    with op.batch_alter_table('player_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_tracking_match_id'))
        batch_op.drop_index(batch_op.f('ix_player_tracking_frame_id'))

    op.drop_table('player_tracking')
    with op.batch_alter_table('player_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_metrics_match_id'))

    op.drop_table('player_metrics')
    with op.batch_alter_table('frames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frames_match_id'))

    op.drop_table('frames')
    with op.batch_alter_table('calibration_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_status_valid'))
        batch_op.drop_index(batch_op.f('ix_calibration_status_match_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_status_frame_start'))

    op.drop_table('calibration_status')
    op.drop_table('matches')
    # ### end Alembic commands ###
