import {
  Chip,
  ConfidenceBadge,
  Disclaimer,
  MetaRow,
  Panel,
  PanelGrid,
  SubHeading,
} from './Primitives.jsx';
import { EmptyState } from './States.jsx';

const SEVERITY_TONE = { major: 'bad', moderate: 'warn', minor: 'neutral' };

/**
 * Renders a CoachReportResponse.
 *
 * Only `narrative` is LLM-generated; the findings, game plan and
 * unavailable-metric list are computed deterministically upstream. The
 * layout keeps that split visible -- measured facts are shown as data with
 * their supporting metrics attached, and the narrative is labelled as the
 * one generated field -- so a coach can always see what the numbers were
 * before a model described them.
 */
export function CoachReport({ report }) {
  if (!report) {
    return (
      <EmptyState
        title="No Coach Report"
        message="A coach report is built after video processing completes for this match."
      />
    );
  }

  const plan = report.game_plan;
  const timeline = report.timeline_sections;
  const coveragePct = Number.isFinite(report.coverage)
    ? `${(report.coverage * 100).toFixed(1)}%`
    : '—';

  return (
    <div className="dash-coach-report">
      <div className="dash-coach-header">
        <Chip tone={report.is_partial ? 'warn' : 'good'}>
          {report.is_partial ? 'Partial report' : 'Full report'}
        </Chip>
        <MetaRow label="metric coverage">{coveragePct}</MetaRow>
        <MetaRow label="model">{report.model_used || '—'}</MetaRow>
      </div>

      {report.is_partial && plan?.partial_reason ? (
        <Disclaimer>
          This report is partial: {plan.partial_reason}. Treat every conclusion
          below as provisional — the missing measurements are listed at the end.
        </Disclaimer>
      ) : null}

      <SubHeading>Tactical Read</SubHeading>
      {report.findings?.length ? (
        <PanelGrid columns={2}>
          {report.findings.map((finding) => (
            <Panel
              key={`${finding.area}-${finding.supporting_metrics.join(',')}`}
              title={finding.area.replace(/_/g, ' ')}
              subtitle={finding.assessment}
              tone={
                finding.assessment === 'weakness'
                  ? 'bad'
                  : finding.assessment === 'strength'
                    ? 'good'
                    : ''
              }
            >
              <p className="dash-finding-text">{finding.explanation}</p>
              <div className="dash-meta-block">
                <ConfidenceBadge confidence={finding.confidence} />
                <MetaRow label="from">{finding.supporting_metrics.join(', ')}</MetaRow>
              </div>
            </Panel>
          ))}
        </PanelGrid>
      ) : (
        <EmptyState
          title="No Findings"
          message="No tactical findings could be derived from the available metrics."
        />
      )}

      {plan ? <GamePlan plan={plan} /> : null}

      <SubHeading>Coach Narrative</SubHeading>
      <p className="dash-absent dash-narrative-note">
        Generated by {report.model_used || 'the configured model'} from the
        measured values above. It is the only generated field on this report.
      </p>
      {report.narrative_warnings?.length ? (
        <Disclaimer>
          The text below made claims the measured data does not support, and a
          corrective regeneration did not clear them. Treat the flagged parts
          as unreliable:{' '}
          {report.narrative_warnings.join('; ')}. The measured sections above
          are unaffected.
        </Disclaimer>
      ) : null}
      <div className="dash-narrative">
        {String(report.narrative || '')
          .split('\n')
          .filter((line) => line.trim())
          .map((line, index) => (
            // eslint-disable-next-line react/no-array-index-key
            <p key={index}>{line}</p>
          ))}
      </div>

      <SubHeading>What Could Not Be Measured</SubHeading>
      <UnavailableMetrics
        reasons={report.unavailable_metrics}
        timeline={timeline}
      />
    </div>
  );
}

function GamePlan({ plan }) {
  return (
    <>
      <SubHeading>Game Plan</SubHeading>

      {plan.proposed_shape ? (
        <div className="dash-shape-block">
          <MetaRow label="proposed shape">
            <strong>{plan.proposed_shape.shape}</strong>
          </MetaRow>
          <p className="dash-finding-text">{plan.proposed_shape.reason}</p>
          {plan.proposed_shape.supporting_metrics?.length ? (
            <MetaRow label="from">
              {plan.proposed_shape.supporting_metrics.join(', ')}
            </MetaRow>
          ) : null}
        </div>
      ) : null}

      <PanelGrid columns={2}>
        <Panel title="Opponent Strengths" subtitle="measured">
          <EvidenceList
            items={plan.opponent_strengths}
            emptyLabel="None measured."
            renderLabel={(item) => item.label}
          />
        </Panel>
        <Panel title="Opponent Weaknesses" subtitle="measured">
          <EvidenceList
            items={plan.opponent_weaknesses}
            emptyLabel="None measured."
            renderLabel={(item) => item.label}
            renderTone={(item) => SEVERITY_TONE[item.severity] || 'neutral'}
            renderBadge={(item) => item.severity}
          />
        </Panel>
      </PanelGrid>

      <SubHeading>Principles of Play</SubHeading>
      {plan.principles?.length ? (
        <ol className="dash-principle-list">
          {plan.principles.map((principle) => (
            <li key={principle.statement}>
              <span className="dash-principle-text">{principle.statement}</span>
              <span className="dash-absent"> {principle.grounded_in}</span>
              <MetaRow label="from">
                {principle.supporting_metrics.join(', ')}
              </MetaRow>
            </li>
          ))}
        </ol>
      ) : (
        <p className="dash-absent">No principles could be derived from the measured data.</p>
      )}

      <SubHeading>In-Game Adjustments</SubHeading>
      {plan.adjustments?.length ? (
        <ol className="dash-adjustment-list">
          {plan.adjustments.map((adjustment) => (
            <li key={adjustment.instruction}>
              <p className="dash-adjustment-text">{adjustment.instruction}</p>
              <div className="dash-meta-block">
                <Chip tone="warn" title="the observed weakness this answers">
                  targets: {adjustment.targets_weakness}
                </Chip>
                <MetaRow label="because">{adjustment.rationale}</MetaRow>
                <MetaRow label="from">
                  {adjustment.supporting_metrics.join(', ')}
                </MetaRow>
              </div>
            </li>
          ))}
        </ol>
      ) : (
        <p className="dash-absent">
          No adjustments could be derived — no measured weakness matched the
          counter-strategy playbook.
        </p>
      )}

      {plan.uncovered_weaknesses?.length ? (
        <Disclaimer>
          Measured weaknesses with no adjustment in the playbook, left open
          rather than answered with a guess:{' '}
          {plan.uncovered_weaknesses.join(', ')}.
        </Disclaimer>
      ) : null}
    </>
  );
}

function EvidenceList({ items, emptyLabel, renderLabel, renderTone, renderBadge }) {
  if (!items?.length) return <p className="dash-absent">{emptyLabel}</p>;
  return (
    <ul className="dash-evidence-list">
      {items.map((item) => (
        <li key={`${item.key}-${item.label}`}>
          <div className="dash-evidence-head">
            <strong>{renderLabel(item)}</strong>
            {renderBadge ? (
              <Chip tone={renderTone ? renderTone(item) : 'neutral'}>
                {renderBadge(item)}
              </Chip>
            ) : null}
          </div>
          <p className="dash-absent">{item.evidence}</p>
          <div className="dash-meta-block">
            <ConfidenceBadge confidence={item.confidence} />
            <MetaRow label="n">{item.sample_size}</MetaRow>
          </div>
        </li>
      ))}
    </ul>
  );
}

/**
 * The unavailable list is long and repetitive on a low-coverage match (one
 * line per player per metric), so it is grouped by metric name. Grouping
 * only -- nothing is dropped, because a metric that silently disappears
 * from this list reads to a coach exactly like a metric that was fine.
 */
function UnavailableMetrics({ reasons, timeline }) {
  if (!reasons?.length) {
    return <p className="dash-absent">Every expected metric was available.</p>;
  }

  const timelineReasons = reasons.filter((r) => r.startsWith('tactical_timeline.'));
  const metricReasons = reasons.filter((r) => !r.startsWith('tactical_timeline.'));

  const grouped = new Map();
  for (const reason of metricReasons) {
    const [name, detail] = reason.split(':');
    const key = name.trim();
    if (!grouped.has(key)) grouped.set(key, { count: 0, detail: (detail || '').trim() });
    grouped.get(key).count += 1;
  }

  return (
    <>
      <ul className="dash-unavailable-list">
        {[...grouped.entries()].map(([name, { count, detail }]) => (
          <li key={name}>
            <strong>{name}</strong>
            {count > 1 ? <Chip tone="neutral">{count} rows</Chip> : null}
            <span className="dash-absent"> {detail}</span>
          </li>
        ))}
      </ul>

      {timelineReasons.length ? (
        <>
          <p className="dash-absent dash-timeline-note">
            Tactical timeline sections{' '}
            {timeline?.available?.length
              ? `(available: ${timeline.available.join(', ')})`
              : '(none available)'}
            :
          </p>
          <ul className="dash-unavailable-list">
            {timelineReasons.map((reason) => (
              <li key={reason}>
                <span className="dash-absent">{reason}</span>
              </li>
            ))}
          </ul>
        </>
      ) : null}
    </>
  );
}

export default CoachReport;
